# Generated by Django 5.1.7 on 2025-03-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="书名")),
                ("author", models.CharField(max_length=100, verbose_name="作者")),
                ("category", models.CharField(max_length=50, verbose_name="类型")),
                (
                    "added_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否被删除"),
                ),
                (
                    "click_count",
                    models.PositiveIntegerField(default=0, verbose_name="点击量"),
                ),
                (
                    "read_duration",
                    models.PositiveIntegerField(default=0, verbose_name="阅读时长"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="简介"),
                ),
                (
                    "cover_url",
                    models.URLField(blank=True, null=True, verbose_name="封面链接"),
                ),
            ],
        ),
    ]
