# Generated by Django 5.1.7 on 2025-03-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="cover_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="封面链接"
            ),
        ),
    ]
