# Generated by Django 5.1.7 on 2025-03-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_alter_books_cover_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="cover_url",
            field=models.ImageField(
                blank=True,
                default="/books/default.jpg",
                null=True,
                upload_to="books",
                verbose_name="封面链接",
            ),
        ),
    ]
