# Generated by Django 5.1.7 on 2025-03-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0004_alter_books_cover_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="用户号"
                    ),
                ),
                ("username", models.CharField(max_length=100, verbose_name="用户名字")),
                ("age", models.PositiveIntegerField(verbose_name="年纪")),
                ("points", models.PositiveIntegerField(default=0, verbose_name="积分")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "myth_duration",
                    models.PositiveIntegerField(default=0, verbose_name="神话观看总时长"),
                ),
                (
                    "xianxia_duration",
                    models.PositiveIntegerField(default=0, verbose_name="仙侠观看总时长"),
                ),
                (
                    "wuxia_duration",
                    models.PositiveIntegerField(default=0, verbose_name="武侠观看总时长"),
                ),
                (
                    "scifi_duration",
                    models.PositiveIntegerField(default=0, verbose_name="科幻观看总时长"),
                ),
                (
                    "mystery_duration",
                    models.PositiveIntegerField(default=0, verbose_name="悬疑观看总时长"),
                ),
                (
                    "historical_duration",
                    models.PositiveIntegerField(default=0, verbose_name="古代观看总时长"),
                ),
                (
                    "modern_duration",
                    models.PositiveIntegerField(default=0, verbose_name="现代观看总时长"),
                ),
                (
                    "total_duration",
                    models.PositiveIntegerField(default=0, verbose_name="观看所有图书的总时长"),
                ),
            ],
        ),
    ]
