# Generated by Django 5.1.7 on 2025-03-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0005_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="/avatars/default.jpg",
                null=True,
                upload_to="avatars/",
                verbose_name="用户头像",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="password",
            field=models.CharField(
                default="123456", max_length=128, verbose_name="用户密码"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=100, unique=True, verbose_name="用户名字"),
        ),
    ]
