# Generated by Django 5.1.7 on 2025-03-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0006_users_avatar_users_password_alter_users_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="img",
            field=models.ImageField(default="/ad/default.png", upload_to="ad"),
        ),
        migrations.AlterField(
            model_name="books",
            name="cover_url",
            field=models.ImageField(
                blank=True,
                default="/books/default.png",
                null=True,
                upload_to="books",
                verbose_name="封面链接",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="/avatars/default.png",
                null=True,
                upload_to="avatars/",
                verbose_name="用户头像",
            ),
        ),
    ]
