# Generated by Django 5.1.7 on 2025-03-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0007_alter_ad_img_alter_books_cover_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="people_count",
            field=models.PositiveIntegerField(default=0, verbose_name="评分人数"),
        ),
        migrations.AddField(
            model_name="books",
            name="rate",
            field=models.FloatField(default=0.0, verbose_name="评分"),
        ),
    ]
