# Generated by Django 5.1.7 on 2025-03-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0008_books_people_count_books_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="rate",
            field=models.FloatField(default=5.0, verbose_name="评分"),
        ),
    ]
