# Generated by Django 5.1.7 on 2025-03-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0010_alter_books_people_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                ("username", models.CharField(max_length=100, verbose_name="用户名")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发表时间"),
                ),
            ],
        ),
    ]
