# Generated by Django 5.1.7 on 2025-03-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0011_discussion"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_books_by_user",
                to="app01.users",
                verbose_name="喜欢这本书的用户",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="liked_books",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_users_by_book",
                to="app01.books",
                verbose_name="用户喜欢的书",
            ),
        ),
    ]
