# Generated by Django 5.1.7 on 2025-04-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0012_books_liked_by_users_liked_books"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否被删除"),
        ),
    ]
