# Generated by Django 5.1.7 on 2025-04-05 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0014_bookreview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="books",
            options={"verbose_name": "书库", "verbose_name_plural": "书库"},
        ),
    ]
