# Generated by Django 5.1.7 on 2025-04-05 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0015_alter_books_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "书评",
                "verbose_name_plural": "书评",
            },
        ),
        migrations.AlterModelOptions(
            name="discussion",
            options={"verbose_name": "讨论区", "verbose_name_plural": "讨论区"},
        ),
        migrations.AlterModelOptions(
            name="users",
            options={"verbose_name": "用户", "verbose_name_plural": "用户"},
        ),
    ]
