# Generated by Django 5.1.7 on 2025-04-05 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0016_alter_bookreview_options_alter_discussion_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={"verbose_name": "广告", "verbose_name_plural": "广告"},
        ),
    ]
